### ISSUE TITLE
Can you share video tutorial of using this?

### ISSUE THREAD

**Issue by sammathur4** [Nithin005/lecturenotes.in-dl.tampermonkey#1]
Can you share a video of how to use this?

**Comment by Nithin005** [comment]
1. get tampermonkey video tutorial -> https://www.tampermonkey.net/faq.php#Q100
2. go to https://greasyfork.org/en/scripts/414016-lecturenotes-dl and click "install this script" button
3. A new page opens, click the install button
 ![image](https://user-images.githubusercontent.com/54359718/96712509-e283cd00-13bc-11eb-9906-f9a4b2530f1e.png)
4. the Script is now installed. 
5. Now Go to any lecturenotes.in Notes and click "read now" 
6. A download button will appear in top right (the script injects that button into the website), click it to start download

**Comment by Nithin005** [comment]
Download button looks like this 
![image](https://user-images.githubusercontent.com/54359718/96712285-86b94400-13bc-11eb-869f-f662e11a1200.png)

**Comment by sammathur4** [comment]
It isn't working for me

**Comment by Nithin005** [comment]
is the button visible for you?
send me the notes link u are trying to download

**Comment by sammathur4** [comment]
https://lecturenotes.in/m/15529?reading=true&continue=1

**Comment by Nithin005** [comment]
i have fixed the issue.
go to https://greasyfork.org/en/scripts/414016-lecturenotes-dl and click "Reinstall version 0.1"
then click install

**Comment by vj-abishek** [comment]
Does any error still exist? it is working for me
