### ISSUE TITLE
Doesn't Work at all!

### ISSUE THREAD

**Issue by marhf** [Nithin005/lecturenotes.in-dl.tampermonkey#2]
The idea of creating this tool is really awesome...but it isn't working as I expected..

When I hit the download button, It goes all the way down to the last page and says 'Downloaded'...but where is the downloaded file... destination?
I need the notes badly!

And it also shows a bug :![IMG20201220195900.jpg](https://user-images.githubusercontent.com/63101457/102715815-d1dcce00-42fd-11eb-8227-fbb915ee93d4.jpg)

Kindly help me out with it..

By the wat

**Comment by Nithin005** [comment]
what browser are you using?
Can u send me the link of the book u are trying to download?
Are u using tampermonkey to run the script?
Try this firefox extension: https://addons.mozilla.org/en-US/firefox/addon/lecturenotes-downloader/ as an alternative

**Comment by marhf** [comment]
> what browser are you using?
> Can u send me the link of the book u are trying to download?
> Are u using tampermonkey to run the script?
> Try this firefox extension: https://addons.mozilla.org/en-US/firefox/addon/lecturenotes-downloader/ as an alternative

Be it any notes, it's the same
BTW I am using EDGE 87 or Chrome 87.

And yes I am using TamperMonkey..latest version.

https://lecturenotes.in/m/14508?reading=true

Tried on this book, but no luck!

**Comment by Nithin005** [comment]
Its working for me. After clicking download, it auto scrolls down to load all the pages. then it will create a pdf file and trigger the download window.Plz check if the pdf  files are there in download directories

try the firefox extension if possible as an alternative: Try this firefox extension: https://addons.mozilla.org/en-US/firefox/addon/lecturenotes-downloader/

**Comment by marhf** [comment]
> Its working for me. After clicking download, it auto scrolls down to load all the pages. then it will create a pdf file and trigger the download window.Plz check if the pdf  files are there in download directories
> 
> try the firefox extension if possible as an alternative: Try this firefox extension: https://addons.mozilla.org/en-US/firefox/addon/lecturenotes-downloader/

That's the thing, it doesn't trigger the download window...I'll try the Firefox Extension and let you know.

**Comment by vivek-gite** [comment]
same problem i am facing here please help!

**Comment by Nithin005** [comment]
@vivek-gite Can u share more detail about the problem u are facing?
try this alternative: https://addons.mozilla.org/en-US/firefox/addon/lecturenotes-downloader/

**Comment by Kript0r3x** [comment]
It is working for me with tampermonkey in chrome.

**Comment by skibzoy** [comment]
it isnt working . the pages get loaded ,the button turns to dowload now  and instantly returns back to download. moreover i am unable to locate the directory where the file has been downloaded , i have checked default download directory set in chrome but nope i dont find my downloaded file. firefox one didint even showed download button i tried that too
 this was the file i was trying to download  https://lecturenotes.in/m/45610-note-for-internet-of-things-iot-by-pratik-tawale?reading=true

**Comment by Nithin005** [comment]
@skibzoy can you share the console logs after pressing the download button.
I tried the file you were trying to download, It is working in my browser.

1, It should autoscroll down to load the pages. I guess that isnt working as expected. Maybe manually scroll the webpage to load all the pages. Then, Click Download and wait for few sec, it should download. OR
2, JSPDF library should be injected into the webpage for PDF generation. Maybe JSPDF isnt getting injected.

**Comment by skibzoy** [comment]
i have attached the screen recordng for the file i was trying , have attached console files too
https://share.vidyard.com/watch/cgKBeKCTVQzcKM1c2Ke31p?

https://lecturenotes.in/m/45610-note-for-internet-of-things-iot-by-pratik-tawale?reading=true  , this was the link
![Screenshot (76)](https://user-images.githubusercontent.com/79938008/109861319-34026980-7c85-11eb-819c-c5d9a3e96e10.png)
![Screenshot (78)](https://user-images.githubusercontent.com/79938008/109861346-395fb400-7c85-11eb-9bce-3c7df1dd971e.png)
![Screenshot (77)](https://user-images.githubusercontent.com/79938008/109861368-3ebcfe80-7c85-11eb-9dc4-bc2cfbb72751.png)

**Comment by Nithin005** [comment]
@skibzoy try this updated script: https://greasyfork.org/en/scripts/414016-lecturenotes-dl?version=906746

**Comment by Nithin005** [comment]
^^ The above link has been updated to link to the right version.
