### ISSUE TITLE
Help me bro plz 

### ISSUE THREAD

**Issue by Getmanish** [Nithin005/lecturenotes.in-dl.tampermonkey#5]
I want to download notes but i have no computer or laptop. Bro can you plz download notes for me and then send me.

**Comment by Nithin005** [comment]
Hey I have Updated the README. Check if its working.

**Comment by Getmanish** [comment]
Bro i have only my mobile.

**Comment by Nithin005** [comment]
I have added instructions for android just now in README. Try it. You will need to download a 120 mb file onetime for it. After which you can download most lecturenotes.in notes easily.

This tool is for personal use only. So, I won't share the files downloaded. 

Sry for the inconvenience.

**Comment by Getmanish** [comment]
Prime notes are not downloading.

**Comment by Nithin005** [comment]
Sorry, prime notes cant be downloaded. Only non-prime notes.
